# Generated by Django 3.1.1 on 2020-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacancies', '0003_auto_20201204_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ImageField(upload_to='galery'),
        ),
    ]
