# Generated by Django 3.1.1 on 2020-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacancies', '0004_auto_20201206_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shortDesc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
